theme: jekyll-theme-minimal
title: [Eric Keenan]
description: [Glaciologist â˜ƒï¸ | Numerical Modeler ğŸ’» | Graduate Student ğŸ‘¨â€ğŸ“ [@CUBoulderATOC](https://www.colorado.edu/atoc/) studying Antarctic surface mass balance ğŸ§ğŸ‡¦ğŸ‡¶ [he/him]]

